name: publish-test-deltas
description: A wrapper around EnricoMi's publish-unit-test-result-action.
inputs:
  # test-results/**/*.xml
  # test-results/**/*.trx
  # test-results/**/*.json
  files_pattern:
    description: test results files to collect and publish
    required: true

  runs-on:
    description: OS to run the action on
    required: false
    default: ubuntu-latest

runs:
  using: composite
  steps:
    - name: publish-unit-test-result-action
      uses: EnricoMi/publish-unit-test-result-action@v2.18.0
      if: always()
      # if: (success() || failure()) && startsWith(${{ inputs.runs-on }}, 'ubuntu') # FIXME
      with:
        files: ${{ inputs.files_pattern }}

    # FIXME
    # - name: publish-unit-test-result-action @ macos
    #   uses: EnricoMi/publish-unit-test-result-action/macos@v2.18.0
    #   if: (success() || failure()) && startsWith(${{ inputs.runs-on }}, 'macos')
    #   with:
    #     files: ${{ inputs.files_pattern }}

    # - name: publish-unit-test-result-action @ windows
    #   uses: EnricoMi/publish-unit-test-result-action/windows@v2.18.0
    #   if: (success() || failure()) && startsWith(${{ inputs.runs-on }}, 'windows')
    #   with:
    #     files: ${{ inputs.files_pattern }}
