name: test-reporter
description: A wrapper around dorny's test-reporter.
inputs:
  name:
    description: step name
    required: false
    default: Unit Tests

  reporter:
    description: Test report format
    required: false
    default: jest-junit

  files_pattern:
    description: test results files to collect and publish
    required: false
    default: junit.xml

runs:
  using: composite
  steps:
    - name: test-reporter
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.files_pattern }}
        reporter: ${{ inputs.reporter }}
