name: actions/publish-test-deltas
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
permissions:
  checks: write
  pull-requests: write

jobs:
  junit-xml:
    name: jest-junit.xml
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest

          # FIXME
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          name: actions/publish-test-deltas:jest-junit.xml @ ${{ matrix.OS }}
          runs-on: ${{ matrix.OS }}
          files_pattern: assets/test-results/jest/junit.xml
