name: actions/publish_test-results_junit-xml
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  publish_test-results_junit-xml:
    name: publish test-results jest-junit.xml
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish_test-results_junit-xml
        with:
          name: jest-junit.xml @ ${{ matrix.OS }}
          files_pattern: assets/test-results/jest/junit.xml
