name: actions/publish_test-results_junit-xml
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  # TODO Make a matrix
  publish_test-results_junit-xml:
    name: publish test-results jest-junit.xml
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish_test-results_junit-xml
        with:
          name: publish test-results jest-junit.xml
          files_pattern: assets/test-results/jest/junit.xml
