name: actions/junit
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  junit:
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest

          # FIXME
          # - macos-latest
          # - windows-latest
    name: Upload jest-junit.xml
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/junit
        with:
          name: jest-junit.xml @ ${{ matrix.OS }}
          files_pattern: assets/test-results/jest/junit.xml
