name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  lint:
    uses: percebus/github-actions-npm/.github/workflows/npm_run_lint.yml@main

  test-reporter_jest-junit:
    needs: lint
    name: test-reporter jest-junit.xml
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/test-reporter
        with:
          name: test-reporter jest-junit.xml @ ${{ matrix.OS }}
          reporter: jest-junit
          files_pattern: assets/test-results/jest/junit.xml

  publish-test-results_junit-xml:
    needs: lint
    name: publish-test-results jest-junit.xml
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-results
        with:
          name: publish test-results jest-junit.xml
          runs-on: ${{ matrix.OS }}
          files_pattern: assets/test-results/jest/junit.xml

  # TODO Make a matrix
  publish_test-results_junit-xml:
    needs: lint
    name: publish test-results jest-junit.xml
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish_test-results_junit-xml
        with:
          name: publish test-results jest-junit.xml
          files_pattern: assets/test-results/jest/junit.xml
