name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm run lint
        run: npm run lint
