name: Verify
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    uses: percebus/github-actions-npm/.github/workflows/npm_run_lint.yml@main
