name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  lint:
    uses: percebus/github-actions-npm/.github/workflows/npm_run_lint.yml@main
