name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    uses: percebus/github-actions-npm/.github/workflows/npm_run_lint.yml@main

  # TODO Make a matrix
  jest-junit:
    needs: npm_run_lint
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/test-reporter
        with:
          step_name: Unit Tests
          reporter: jest-junit
          files_path: junit.xml
