name: jest ci > junit.xml
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  npm_test:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-node/.github/actions/npm_install@main

      - name: npm test
        run: npm test
      - uses: ./.github/actions/test-reporter
        with:
          name: Unit Tests
          reporter: jest-junit
          files_pattern: junit.xml
