name: Test actions/publish-test-deltas
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
permissions:
  checks: write
  pull-requests: write

env:
  FILE_FORMAT: jest-junit
  FILES_PATTERN: assets/test-results/jest/junit.xml

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}

  os_matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest

          # FIXME
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.OS }}
    name: ${{ matrix.OS }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          runs-on: ${{ matrix.OS }}
          files_pattern: ${{ env.FILES_PATTERN }}

  files_pattern_matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        files_pattern:
          - assets/test-results/jest/junit.xml
          - assets/**/jest/junit.xml
          - "**/*junit.xml"
    name: "files_pattern: ${{ matrix.files_pattern }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ matrix.files_pattern }}
