name: Test actions/junit
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

env:
  FILES_PATTERN: assets/test-results/jest/junit.xml

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/junit
        with:
          files_pattern: ${{ env.FILES_PATTERN }}

  os_matrix:
    needs: default
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        # Different OS
        OS:
          - ubuntu-latest

          # FIXME
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.OS }}
    name: "@ ${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/junit
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          # test-reporter
          tests_name: actions/junit:${{ env.REPORTER }} @ ${{ matrix.OS }}
          # test-summary
          summary_title: actions/junit:Test Summary @ ${{ matrix.OS }}
          # publish-test-deltas
          # publish-test-deltas: "true"

  test-reporter_only_list_matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        list-suites:
          - all
          - failed

        list-tests:
          - all
          - failed
          - none
    name: list-suites & tests
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/junit
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          # test-reporter
          reporter: ${{ env.REPORTER }}
          tests_name: "actions/junit:${{ env.REPORTER }} list-suites:${{ matrix.list-suites }} list-tests:${{ matrix.list-tests }}"
          list-suites: ${{ matrix.list-suites }}
          list-tests: ${{ matrix.list-tests }}
          # test-summary
          summary_title: ""
          # publish-test-deltas
          publish-test-deltas: "false"

  publish-test-deltas_only_matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        publish-test-deltas:
          - "true"
          - "false"

    name: "publish-test-deltas: ${{ matrix.publish-test-deltas }}"
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/junit
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          reporter: ""
          summary_title: ""
          publish-test-deltas: ${{ matrix.publish-test-deltas }}
