name: Test actions/test-summary
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  FILES_PATTERN: assets/test-results/jest/junit.xml

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/test-summary
        with:
          files_pattern: ${{ env.FILES_PATTERN }}

  os_matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.OS }}
    name: "@ ${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/test-summary
        with:
          name: actions/test-summary:jest-junit.xml @ ${{ matrix.OS }}
          title: actions/test-summary:Test Summary @ ${{ matrix.OS }}
          files_pattern: ${{ env.FILES_PATTERN }}
