name: Test actions/publish-test-deltas

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
permissions:
  checks: write
  pull-requests: write

env:
  FILE_FORMAT: jest-junit
  FILES_PATTERN: assets/test-results/jest/junit.xml

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          check_name: "actions/publish-test-deltas: default"
          comment_mode: off

  os__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # Different OS
        OS:
          - ubuntu-latest

          # FIXME
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.OS }}
    name: "@${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          runs-on: ${{ matrix.OS }}
          files_pattern: ${{ env.FILES_PATTERN }}
          check_name: "actions/publish-test-deltas @ ${{ matrix.OS }}"
          comment_mode: off

  files_pattern__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        files_pattern:
          - assets/test-results/jest/junit.xml
          - assets/**/jest/junit.xml
          - "**/*junit.xml"
    name: "files_pattern: ${{ matrix.files_pattern }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ matrix.files_pattern }}
          comment_mode: off
          check_name: "actions/publish-test-deltas: files_pattern:${{ matrix.files_pattern }}"

  comment_mode__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        comment_mode:
          - always
          - changes
          - changes in failures
          - changes in errors
          - failures
          - errors
          - "off"
    runs-on: ubuntu-latest
    name: "comment_mode: ${{ matrix.comment_mode }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          comment_title: "comment_mode: ${{ matrix.comment_mode }}"
          comment_mode: ${{ matrix.comment_mode }}
          check_name: "actions/publish-test-deltas: comment_mode:${{ matrix.comment_mode }}"

  comment_title__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        comment_title:
          - "comment_title: Bananas"
          - "comment_title: Pijamas"
    runs-on: ubuntu-latest
    name: ${{ matrix.comment_title }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          comment_title: ${{ matrix.comment_title }}
          check_name: "actions/publish-test-deltas: ${{ matrix.comment_title }}"

  check_name__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        check_name:
          - "actions/publish-test-deltas: Checkity"
          - "actions/publish-test-deltas: Checked"
    runs-on: ubuntu-latest
    name: "check_name: ${{ matrix.check_name }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          check_name: ${{ matrix.check_name }}
          comment_mode: off

  ignore_runs__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        ignore_runs:
          - true
          - false
    runs-on: ubuntu-latest
    name: "ignore_runs: ${{ matrix.ignore_runs }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/publish-test-deltas
        with:
          files_pattern: ${{ env.FILES_PATTERN }}
          ignore_runs: ${{ matrix.ignore_runs }}
          comment_mode: off
          check_name: "actions/publish-test-deltas: ignore_runs:${{ matrix.ignore_runs }}"
